# Generated by Django 5.0.3 on 2024-11-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_application_jobapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
